/// Thrown when the secret for [credentialReference] cannot be found.
class JournalSecretUnavailableException implements Exception {
  JournalSecretUnavailableException(this.credentialReference);

  final String credentialReference;

  @override
  String toString() =>
      'JournalSecretUnavailableException($credentialReference)';
}

/// Stores and retrieves per-journal secret bytes (journal DEKs).
///
/// On real devices this is backed by the platform Keystore/Keychain.
/// Test implementations may use an in-memory map.
abstract class JournalSecretStore {
  /// Generates and persists a new random secret for [credentialReference].
  ///
  /// Returns the generated bytes.
  Future<List<int>> createSecret(String credentialReference);

  /// Loads the secret bytes for [credentialReference].
  ///
  /// Throws [JournalSecretUnavailableException] if not found.
  Future<List<int>> loadSecret(String credentialReference);

  /// Deletes the secret for [credentialReference].
  Future<void> deleteSecret(String credentialReference);
}
